### ISSUE TITLE
`Gene Info` parameter is not implemented

### ISSUE THREAD

**Issue by hanbinlu** [CSOgroup/CALDER#2]
Hi CALDER developers,

Thank you for developing the nice tool! As far as I know, CALDER determined the PC1 sign by gene density as below. It currently points to "TxDb.Hsapiens.UCSC.hg19.knownGene.rds" and cannot be changed.

```
gene_info_file = system.file("extdata", "TxDb.Hsapiens.UCSC.hg19.knownGene.rds", package = 'CALDER')
```

Thank you,
Hanbin

**Comment by YuanlongLiu** [comment]
> Hi CALDER developers,
> 
> Thank you for developing the nice tool! As far as I know, CALDER determined the PC1 sign by gene density as below. It currently points to "TxDb.Hsapiens.UCSC.hg19.knownGene.rds" and cannot be changed.
> 
> ```
> gene_info_file = system.file("extdata", "TxDb.Hsapiens.UCSC.hg19.knownGene.rds", package = 'CALDER')
> ```
> 
> Thank you, Hanbin

Thanks for pointing it out. Yes, the current version includes only hg19, but in principle Calder can be applied to many other species and this is on the to-do list. If you need to run Calder on a specific organism, can email me and I update a test version for you.

**Comment by shuzhangcourage** [comment]
Dear relative developers,
Like your tool very much, could you generate hg38 rds? It would be perfect ! 
Thank you very much!
Shu

**Comment by hanbinlu** [comment]
As a workaround, I created my interested genome's TxDb rds file and replaced it with Calder's.

```
library(CALDER)
BiocManager::install("TxDb.Mmusculus.UCSC.mm10.knownGene")
library(TxDb.Mmusculus.UCSC.mm10.knownGene)
saveRDS(genes(TxDb.Mmusculus.UCSC.mm10.knownGene), file="~/anaconda3/envs/r_calder/lib/R/library/CALDER/extdata/TxDb.Hsapiens.UCSC.hg19.knownGene.rds")
```
