### ISSUE TITLE
Straw output as input to CALDER

### ISSUE THREAD

**Issue by yeroslaviz** [CSOgroup/CALDER#5]
Thanks for a great tool. I have a question about using the tables created with the tool [straw](https://github.com/aidenlab/straw), which extracts the hic data from the hic files created with juicer in a fast and easy way.

The problem is that straw creates column header to the table in this way:

```
         x       y counts
1: 2500000 2500000   9313
2: 2500000 5000000    230
...
```

But when using this as input to CALDER, it throws an error. 

```
>>>> Begin process contact matrix and compute correlation score at: 2022-06-23 15:46:47
Error in eval(e, x, parent.frame()) : object 'V3' not found
```

I guess, this is because CALDER expect the table to have no column names, which then R creates automatically by creating the giving the third column the title `V3`. 

Is it hard coded in the function?
Is there a way to just make it read the third column, without expecting an exact match in the column name?

thanks
Assa

**Comment by YuanlongLiu** [comment]
Yes it expects table with no column names, as generated by the 'dump' command. Just modified the code to accept table with column names
